### ISSUE TITLE
How to set colors on pie slices?

### ISSUE THREAD

**Issue by dbkaplun** [react-d3/react-d3-basics#20]

**Comment by chilijung** [comment]
hi @dbkaplun, you can setup your slices color in `chartSeries` props, add a key called `color` in the field you want to add, and also you can control your styles in `style` key.

here is an example: https://github.com/react-d3/react-d3-basic/blob/master/example/src/pie.jsx#L17-L49

```
chartSeries = [
      {
        "field": "<5",
        "name": "less than 5",
        "color": "red",
        "style": {
          "fill-opacity": .2
        }
      },...
    ]
```
