### ISSUE TITLE
Labels are gone (at least in BarGroup)

### ISSUE THREAD

**Issue by asaf** [react-d3/react-d3-basics#25]
Hey,

No matter what I tried, labels are not shown,
I tried to clone the repo as is, and hit the `example/bar_group.html`, same result,

Any clue?
Thanks.

**Comment by chilijung** [comment]
https://github.com/react-d3/react-d3-example/blob/f9b5a23efc0847ed200f37ff702e60ffb668924a/simple/bar/bar.js#L27-L39

here is a demo.

You have to set lavels via props `xLabel`, `yLabel`
