### ISSUE TITLE
Allow passing down of react-d3-core props from parent charts

### ISSUE THREAD

**Issue by lord-xeon** [react-d3/react-d3-basics#26]
I'd like to format the x & y axis of my LineChart, but the built in LineChart module doesn't pass anything into those components.  This makes setting up my own custom charts more difficult as I have to piece together what I want to display.

**Comment by chilijung** [comment]
@lord-xeon, all the props you set to x, y axis will be passed to xaxis and yaxis. 

I'll clone the props and send to it's children

https://github.com/react-d3/react-d3-shape/blob/master/src/chart.jsx#L87-L114
