### ISSUE TITLE
required Proptypes for axis missing from LineChart

### ISSUE THREAD

**Issue by yinghaochan** [react-d3/react-d3-basics#27]
https://github.com/react-d3/react-d3-core/blob/master/src/axis/xaxis.jsx
Following the Docs demo, it doesn't seem LineChart passes any props.

https://github.com/react-d3/react-d3-basic/blob/master/src/line.jsx

**Comment by chilijung** [comment]
Yes it did.

https://github.com/react-d3/react-d3-basic/blob/master/src/line.jsx#L17-L20

```
<Chart>
```

will clone all the props and send to it's children. See here.

https://github.com/react-d3/react-d3-shape/blob/master/src/chart.jsx#L87-L114

**Comment by yinghaochan** [comment]
My bad. That's the error I'm getting, though, even with a line for line copy of the demo code.
